# Uncomment the next line to define a global platform for your project
 platform :ios, ‘8.0’

target 'Indianapolis Coffee Guide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
inhibit_all_warnings!

  # Pods for Indianapolis Coffee Guide

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth’
  pod 'Firebase/Storage’


  target 'Indianapolis Coffee GuideUITests' do
    inherit! :search_paths
	pod ‘Firebase’
    # Pods for testing
  end

end
