# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Indianapolis Coffee Guide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Indianapolis Coffee Guide

  pod 'Firebase/Core'
  target 'Indianapolis Coffee GuideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Indianapolis Coffee GuideUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
